version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: smart-parking-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: smart-parking-backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/smart-parking?authSource=admin
      - JWT_SECRET=secret
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: smart-parking-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mongo_data:
